// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfcB03BMc12MYHYeFWJ7bFr7rGS0AYdo0',
    appId: '1:741534974151:web:a99cb13b754c5cf57c7ee2',
    messagingSenderId: '741534974151',
    projectId: 'chatapp-293f8',
    authDomain: 'chatapp-293f8.firebaseapp.com',
    storageBucket: 'chatapp-293f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnDg5oot28ROeLSHf8NoLbB7sSIxKNzHk',
    appId: '1:741534974151:android:1567ca10b1733aeb7c7ee2',
    messagingSenderId: '741534974151',
    projectId: 'chatapp-293f8',
    storageBucket: 'chatapp-293f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqQBEM8i5Bm01xMhNntnydwFScKs07NPQ',
    appId: '1:741534974151:ios:7bc14ab643505d2f7c7ee2',
    messagingSenderId: '741534974151',
    projectId: 'chatapp-293f8',
    storageBucket: 'chatapp-293f8.firebasestorage.app',
    iosBundleId: 'com.example.memesh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqQBEM8i5Bm01xMhNntnydwFScKs07NPQ',
    appId: '1:741534974151:ios:7bc14ab643505d2f7c7ee2',
    messagingSenderId: '741534974151',
    projectId: 'chatapp-293f8',
    storageBucket: 'chatapp-293f8.firebasestorage.app',
    iosBundleId: 'com.example.memesh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfcB03BMc12MYHYeFWJ7bFr7rGS0AYdo0',
    appId: '1:741534974151:web:6379bcd77d6222f37c7ee2',
    messagingSenderId: '741534974151',
    projectId: 'chatapp-293f8',
    authDomain: 'chatapp-293f8.firebaseapp.com',
    storageBucket: 'chatapp-293f8.firebasestorage.app',
  );
}
